### ISSUE TITLE
Uncaught TypeError: this.$img.cropper is not a function

### ISSUE THREAD

**Issue by RobinMalfait** [roadmanfong/react-cropper#6]
Hello

I'm getting this error all the time: Uncaught TypeError: this.$img.cropper is not a function
And I have jQuery loaded, any thoughts?

**Comment by vinesone** [comment]
Me too. I had to edit the main js file to get it to work in my project.

**Comment by RobinMalfait** [comment]
@vinesone I'm using ES6 and WebPack, could it be that jQuery is not loaded for some reason?

**Comment by RobinMalfait** [comment]
@vinesone P.S.: how/what did you change?

**Comment by vinesone** [comment]
@RobinMalfait : Hey there, I am not using Es6 or WebPack, I am using it with reactify. I do not recommend doing this, especially if your work is going into a production environment or if you are working on a team... but you may be able to get it to work by commenting out: var _jquery = require('jquery'); and  var $ = _interopRequireDefault(_jquery) in the /dist/react-cropper.js file  ( I had to do this for both jquery and react to get it working with my set up... ) I am pretty sure this is because of the way I am handling dependencies within my project. Anyone have an ideas?

**Comment by RobinMalfait** [comment]
What I did to fix it:

Copy & paste the code of this plugin in my own component file, and it works.

Pretty weird...

**Comment by roadmanfong** [comment]
Please try to `npm install jquery` before `npm install react-cropper`.

I think it's because it installed another jquery module inside of react-cropper.

Not sure how to solve this, I'v declared jquery in peerDependencies in `package.json`.
Any advice?

**Comment by kwtnb** [comment]
I was also getting this error using npm.
I fixed the problem as follows.

1. Uninstall react-cropper
1. Declare jquery in your project's package.json dependencies
1. Reinstall react-cropper
